# Combining Twitter and Power Outage data
___

## Imports

In [2]:
import pandas as pd
import time
from datetime import datetime, timedelta

In [3]:
twitter_df = pd.read_csv('../Data/twitter_states_cleaned_2014_19.csv')
power_df = pd.read_csv('../Data/power_outage.csv')

In [4]:
twitter_df.head()

,tweet,location,user_name,time_stamp,num_retweets,num_likes,tweet_word_count,port_tweet,time_location
0,and we could spend the rest of the money on ra...,Alabama,samd9273,2019-10-31 22:11:35,0,0,23,and we could spend the rest of the money on ra...,2019-10-31 22:00:00 | Alabama
1,we sorry to hear the power is out please dm th...,Alabama,alabamapower,2019-10-31 21:53:10,0,0,23,we sorri to hear the power is out pleas dm the...,2019-10-31 21:00:00 | Alabama
2,drx1304 think of how many ducks we could buy w...,Alabama,samd9273,2019-10-31 21:44:15,0,1,13,drx1304 think of how mani duck we could buy wi...,2019-10-31 21:00:00 | Alabama
3,it s spooky season,Alabama,OMGItsBlackout,2019-10-31 18:17:20,0,0,3,it s spooki season,2019-10-31 18:00:00 | Alabama
4,newsom raked in big money from public utility ...,Alabama,deenie7940,2019-10-31 13:58:11,0,0,19,newsom rake in big money from public util he i...,2019-10-31 13:00:00 | Alabama

In [5]:
power_df.head()

,Unnamed: 0,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,state,Hour Event Began,time_location
0,0,January,2014-01-06,19:50:00,01/06/2014,20:44:00,District of Columbia,RFC,Missing,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown,District of Columbia,19,2014-01-06 19:00:00 | District of Columbia
1,1,January,2014-01-06,19:50:00,01/06/2014,20:44:00,Unknown,RFC,Missing,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown,Unknown,19,2014-01-06 19:00:00 | Unknown
2,2,January,2014-01-06,19:52:00,01/06/2014,20:45:00,Delaware,RFC,Missing,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown,Delaware,19,2014-01-06 19:00:00 | Delaware
3,3,January,2014-01-06,20:45:00,01/07/2014,21:00:00,Unknown,RFC,Missing,Public Appeal due to Severe Weather - Cold,Unknown,Unknown,Unknown,20,2014-01-06 20:00:00 | Unknown
4,4,January,2014-01-06,19:50:00,01/06/2014,20:49:00,Pennsylvania,RFC,Missing,Voltage Reduction due to Severe Weather - Cold,200,62000,Pennsylvania,19,2014-01-06 19:00:00 | Pennsylvania

In [6]:
power_df = power_df.drop(columns=['Unnamed: 0', 'Month', 'Alert Criteria', 'Number of Customers Affected',
                                 'Hour Event Began', 'NERC Region', 'Alert Criteria', 'Area Affected',
                                 'Demand Loss (MW)'])
twitter_df = twitter_df.drop(columns=['tweet_word_count', 'user_name', 'port_tweet', 'num_likes', 'num_retweets'])

In [7]:
print(twitter_df.shape)
print(power_df.shape)

(18990, 4)
(1325, 7)

___
## Merge the two dataframes

In [8]:
df = pd.merge(twitter_df, power_df, on='time_location', how='inner')
df

,tweet,location,time_stamp,time_location,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Event Type,state
0,i guarantee leonardo dicaprio is blackout drun...,New York,2014-03-03 17:46:01,2014-03-03 17:00:00 | New York,2014-03-03,17:25:00,03/03/2014,17:25:00,Suspected Physical Attack,New York
1,my power is out in new york city and if it doe...,New York,2019-07-21 23:57:53,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
2,why my friend in canarsie say they got a blackout,New York,2019-07-21 23:54:03,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
3,power outage greattttt,New York,2019-07-21 23:48:10,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
4,power outage in my part of town,New York,2019-07-21 23:42:19,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
5,ima gonna try to laugh this power outage off b...,New York,2019-07-21 23:42:19,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
6,blackout,New York,2019-07-21 23:38:59,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
7,directvnow on the plus side i am thrilled the ...,New York,2019-07-21 23:37:26,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
8,church service today was going great until the...,New York,2019-07-21 23:30:13,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
9,my neighborhood is experiencing a blackout at ...,New York,2019-07-21 23:18:48,2019-07-21 23:00:00 | New York,2019-07-21,23:00:00,07/22/2019,20:54:00,Severe Weather,New York
10,good morning world time to blackout at nyc pri...,New York,2019-06-30 15:45:25,2019-06-30 15:00:00 | New York,2019-06-30,15:15:00,06/30/2019,16:15:00,Severe Weather,New York
11,davegramana is this blackout all your fault ho...,Washington,2019-07-13 23:47:34,2019-07-13 23:00:00 | Washington,2019-07-13,23:55:00,07/14/2019,13:00:00,Severe Weather,Washington

In [9]:
df.shape

(12, 10)

only 12 matches. check just matching at the date

In [10]:
twitter_df['date_state'] = [f"{post.split('|')[0].split()[0]} | {twitter_df['location'][i]}" 
 for i, post in enumerate(twitter_df['time_location'])]

In [11]:
power_df['date_state'] = [f"{post.split('|')[0].split()[0]} | {power_df['state'][i]}" 
 for i, post in enumerate(power_df['time_location'])]

In [12]:
df = pd.merge(twitter_df, power_df, on='date_state', how='inner')
df.shape

(412, 12)

In [12]:
df.head()

,tweet,location,time_stamp,time_location_x,date_state,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Event Type,state,time_location_y
0,tess catherine one month til blackout,Georgia,2015-01-07 04:13:49,2015-01-07 04:00:00 | Georgia,2015-01-07 | Georgia,2015-01-07,17:00:00,2015-01-08 00:00:00,08:35:00,Severe Weather - Winter,Georgia,2015-01-07 17:00:00 | Georgia
1,whos ready for a power outage at goetz,Georgia,2014-02-21 19:56:38,2014-02-21 19:00:00 | Georgia,2014-02-21 | Georgia,2014-02-21,2:53:00,02/21/2014,21:00:00,Severe Weather - Thunderstorms/High Winds,Georgia,2014-02-21 2:00:00 | Georgia
2,last minute pl blackout shud be fun,Georgia,2014-02-21 19:52:26,2014-02-21 19:00:00 | Georgia,2014-02-21 | Georgia,2014-02-21,2:53:00,02/21/2014,21:00:00,Severe Weather - Thunderstorms/High Winds,Georgia,2014-02-21 2:00:00 | Georgia
3,michaelcisero c monnn blackout cis,Georgia,2014-02-21 17:20:13,2014-02-21 17:00:00 | Georgia,2014-02-21 | Georgia,2014-02-21,2:53:00,02/21/2014,21:00:00,Severe Weather - Thunderstorms/High Winds,Georgia,2014-02-21 2:00:00 | Georgia
4,we are one week away from the blackout party a...,Georgia,2014-02-21 13:29:18,2014-02-21 13:00:00 | Georgia,2014-02-21 | Georgia,2014-02-21,2:53:00,02/21/2014,21:00:00,Severe Weather - Thunderstorms/High Winds,Georgia,2014-02-21 2:00:00 | Georgia

In [13]:
twitter_df.head()

,tweet,location,time_stamp,time_location,date_state
0,and we could spend the rest of the money on ra...,Alabama,2019-10-31 22:11:35,2019-10-31 22:00:00 | Alabama,2019-10-31 | Alabama
1,we sorry to hear the power is out please dm th...,Alabama,2019-10-31 21:53:10,2019-10-31 21:00:00 | Alabama,2019-10-31 | Alabama
2,drx1304 think of how many ducks we could buy w...,Alabama,2019-10-31 21:44:15,2019-10-31 21:00:00 | Alabama,2019-10-31 | Alabama
3,it s spooky season,Alabama,2019-10-31 18:17:20,2019-10-31 18:00:00 | Alabama,2019-10-31 | Alabama
4,newsom raked in big money from public utility ...,Alabama,2019-10-31 13:58:11,2019-10-31 13:00:00 | Alabama,2019-10-31 | Alabama

In [14]:
power_df.head()

,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Event Type,state,time_location,date_state
0,2014-01-06,19:50:00,01/06/2014,20:44:00,Voltage Reduction due to Severe Weather - Cold,District of Columbia,2014-01-06 19:00:00 | District of Columbia,2014-01-06 | District of Columbia
1,2014-01-06,19:50:00,01/06/2014,20:44:00,Voltage Reduction due to Severe Weather - Cold,Unknown,2014-01-06 19:00:00 | Unknown,2014-01-06 | Unknown
2,2014-01-06,19:52:00,01/06/2014,20:45:00,Voltage Reduction due to Severe Weather - Cold,Delaware,2014-01-06 19:00:00 | Delaware,2014-01-06 | Delaware
3,2014-01-06,20:45:00,01/07/2014,21:00:00,Public Appeal due to Severe Weather - Cold,Unknown,2014-01-06 20:00:00 | Unknown,2014-01-06 | Unknown
4,2014-01-06,19:50:00,01/06/2014,20:49:00,Voltage Reduction due to Severe Weather - Cold,Pennsylvania,2014-01-06 19:00:00 | Pennsylvania,2014-01-06 | Pennsylvania

___
## check to see if a tweet is between a range of time event began and date of resoration

In [15]:
al_power = power_df[(power_df['state'] == 'Arizona') | (power_df['state'] == 'Unknown')]
al_power

,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Event Type,state,time_location,date_state
1,2014-01-06,19:50:00,01/06/2014,20:44:00,Voltage Reduction due to Severe Weather - Cold,Unknown,2014-01-06 19:00:00 | Unknown,2014-01-06 | Unknown
3,2014-01-06,20:45:00,01/07/2014,21:00:00,Public Appeal due to Severe Weather - Cold,Unknown,2014-01-06 20:00:00 | Unknown,2014-01-06 | Unknown
9,2014-01-07,21:00:00,01/08/2014,9:00:00,Public Appeal due to Severe Weather - Cold,Unknown,2014-01-07 21:00:00 | Unknown,2014-01-07 | Unknown
19,2014-01-08,5:00:00,01/08/2014,6:30:00,Voltage Reduction due to Severe Weather - Cold,Unknown,2014-01-08 5:00:00 | Unknown,2014-01-08 | Unknown
21,2014-01-13,16:44:00,01/13/2014,16:45:00,Physical Attack - Vandalism,Arizona,2014-01-13 16:00:00 | Arizona,2014-01-13 | Arizona
23,2014-01-16,12:30:00,01/16/2014,13:57:00,Physical Attack - Vandalism,Arizona,2014-01-16 12:00:00 | Arizona,2014-01-16 | Arizona
26,2014-01-18,17:39:00,Unknown,Unknown,Electrical System Islanding,Unknown,2014-01-18 17:00:00 | Unknown,2014-01-18 | Unknown
44,2014-01-29,16:00:00,01/29/2014,16:44:00,Physical Attack - Vandalism,Unknown,2014-01-29 16:00:00 | Unknown,2014-01-29 | Unknown
45,2014-01-30,15:00:00,Unknown,Unknown,Physical Attack - Vandalism,Arizona,2014-01-30 15:00:00 | Arizona,2014-01-30 | Arizona
80,2014-03-17,17:25:00,03/18/2014,0:56:00,Physical Attack - Sabatoge,Arizona,2014-03-17 17:00:00 | Arizona,2014-03-17 | Arizona
112,2014-05-27,11:00:00,05/27/2014,16:53:00,Physical Attack - Vandalism,Arizona,2014-05-27 11:00:00 | Arizona,2014-05-27 | Arizona
118,2014-06-11,9:30:00,06/11/2014,9:31:00,Suspected Physical Attack,Arizona,2014-06-11 9:00:00 | Arizona,2014-06-11 | Arizona
209,2014-11-12,2:59:00,11/12/2014,3:00:00,Suspected Physical Attack - Vandalism,Unknown,2014-11-12 2:00:00 | Unknown,2014-11-12 | Unknown
257,2015-02-05,08:15:00,2015-02-05 00:00:00,08:17:00,Vandalism,Arizona,2015-02-05 8:00:00 | Arizona,2015-02-05 | Arizona
273,2015-02-17,06:20:00,2015-02-17 00:00:00,07:30:00,Vandalism,Arizona,2015-02-17 6:00:00 | Arizona,2015-02-17 | Arizona
281,2015-02-19,14:30:00,2015-02-19 00:00:00,15:20:00,Vandalism,Arizona,2015-02-19 14:00:00 | Arizona,2015-02-19 | Arizona
300,2015-04-07,12:30:00,2015-04-07 00:00:00,17:34:00,System Operations,Unknown,2015-04-07 12:00:00 | Unknown,2015-04-07 | Unknown
367,2015-08-03,08:27:00,2015-08-04 00:00:00,01:18:00,Sabotage,Arizona,2015-08-03 8:00:00 | Arizona,2015-08-03 | Arizona
451,2016-02-26,16:35:00,2016-02-26 00:00:00,20:22:00,Sabotage - Operator Action(s),Arizona,2016-02-26 16:00:00 | Arizona,2016-02-26 | Arizona
553,2016-09-25,12:49:00,2016-09-25 00:00:00,18:20:00,Vandalism,Arizona,2016-09-25 12:00:00 | Arizona,2016-09-25 | Arizona
952,2018-07-30,06:30:00,07/30/2018,23:00:00,Severe Weather,Arizona,2018-07-30 6:00:00 | Arizona,2018-07-30 | Arizona
1188,2019-04-17,19:38:00,04/17/2019,23:52:00,System Operations,Arizona,2019-04-17 19:00:00 | Arizona,2019-04-17 | Arizona
1195,2019-04-25,18:03:00,04/25/2019,18:32:00,Generation Inadequacy,Arizona,2019-04-25 18:00:00 | Arizona,2019-04-25 | Arizona

In [16]:
al_power['Date Event Began'][al_power['state'].index[5]] + " " + al_power['Time Event Began'][al_power['state'].index[5]]

'2014-01-16 12:30:00'

In [17]:
al_twitter = twitter_df[(twitter_df['location'] == 'Arizona')]
al_twitter

,tweet,location,time_stamp,time_location,date_state
72,live darwin is streaming luigi s mansion 3 thi...,Arizona,2019-10-31 21:02:55,2019-10-31 21:00:00 | Arizona,2019-10-31 | Arizona
73,this is the same kind of stupidity that lead t...,Arizona,2019-10-31 20:19:29,2019-10-31 20:00:00 | Arizona,2019-10-31 | Arizona
74,do you get those blackouts when you stand up s...,Arizona,2019-10-31 16:26:31,2019-10-31 16:00:00 | Arizona,2019-10-31 | Arizona
75,newsom raked in big money from public utility ...,Arizona,2019-10-31 13:30:09,2019-10-31 13:00:00 | Arizona,2019-10-31 | Arizona
76,will wildfires mismanagement and blackouts for...,Arizona,2019-10-30 22:03:02,2019-10-30 22:00:00 | Arizona,2019-10-30 | Arizona
77,no worries kathy when it s all over and done t...,Arizona,2019-10-30 15:29:12,2019-10-30 15:00:00 | Arizona,2019-10-30 | Arizona
78,no worries josh just prepare for the next roun...,Arizona,2019-10-30 03:54:58,2019-10-30 03:00:00 | Arizona,2019-10-30 | Arizona
79,preventive blackouts continue in california wh...,Arizona,2019-10-29 20:14:24,2019-10-29 20:00:00 | Arizona,2019-10-29 | Arizona
80,california chaos gov gavin newsom grapples wit...,Arizona,2019-10-29 18:02:18,2019-10-29 18:00:00 | Arizona,2019-10-29 | Arizona
81,check out this interesting article that talks ...,Arizona,2019-10-29 16:48:31,2019-10-29 16:00:00 | Arizona,2019-10-29 | Arizona
82,the comfortable and privileged middle class ge...,Arizona,2019-10-28 17:02:03,2019-10-28 17:00:00 | Arizona,2019-10-28 | Arizona
83,extra batteries check how to prepare for a pow...,Arizona,2019-10-28 16:49:31,2019-10-28 16:00:00 | Arizona,2019-10-28 | Arizona
84,california wildfires burn to prevent power lin...,Arizona,2019-10-28 16:14:05,2019-10-28 16:00:00 | Arizona,2019-10-28 | Arizona
85,blackouts and mass evacuations as kincade fire...,Arizona,2019-10-28 15:26:26,2019-10-28 15:00:00 | Arizona,2019-10-28 | Arizona
86,newsom don t take power outage frustrations ou...,Arizona,2019-10-27 23:48:08,2019-10-27 23:00:00 | Arizona,2019-10-27 | Arizona
87,wonder if they re doing these blackouts trying...,Arizona,2019-10-27 04:31:20,2019-10-27 04:00:00 | Arizona,2019-10-27 | Arizona
88,very enlightening article as to the reasons fo...,Arizona,2019-10-27 04:10:23,2019-10-27 04:00:00 | Arizona,2019-10-27 | Arizona
89,all californians right now getting ready for a...,Arizona,2019-10-27 03:53:04,2019-10-27 03:00:00 | Arizona,2019-10-27 | Arizona
90,new addition to ami aag roster make sure to gi...,Arizona,2019-10-26 16:58:58,2019-10-26 16:00:00 | Arizona,2019-10-26 | Arizona
91,california forced a shut down on rancho seco g...,Arizona,2019-10-26 14:07:48,2019-10-26 14:00:00 | Arizona,2019-10-26 | Arizona
92,california may experience its biggest blackout...,Arizona,2019-10-26 00:13:38,2019-10-26 00:00:00 | Arizona,2019-10-26 | Arizona
93,the sad fact is every fire season fire bugs se...,Arizona,2019-10-25 21:45:05,2019-10-25 21:00:00 | Arizona,2019-10-25 | Arizona
94,i know the question s rhetorical but yeah of c...,Arizona,2019-10-25 07:33:04,2019-10-25 07:00:00 | Arizona,2019-10-25 | Arizona
95,we won t see it till tomorrow because msnbc bl...,Arizona,2019-10-25 03:32:57,2019-10-25 03:00:00 | Arizona,2019-10-25 | Arizona
96,rolling blackouts sweep through northern calif...,Arizona,2019-10-24 14:08:54,2019-10-24 14:00:00 | Arizona,2019-10-24 | Arizona

In [18]:
datetime.strptime(al_twitter['time_stamp'][72], '%Y-%m-%d %H:%M:%S') + timedelta(days=1)

datetime.datetime(2019, 11, 1, 21, 2, 55)

In [19]:
len(twitter_df['location'].unique())

48

In [20]:
t0 = time.time()
twitter_df['target'] = 0
size = len(twitter_df['location'].unique())
counter = 0

# we need to check the locations and times match up so let's make smaller dataframes and check those
for place in twitter_df['location'].unique():
    
    # check Unknown states as well
    state_power_df = power_df[(power_df['state'] == place) | (power_df['state'] == 'Unknown')]
    state_twitter_df = twitter_df[(twitter_df['location'] == place)]
    
    # loop through every tweet in the state twitter df
    for i, tweet_ts in enumerate(state_twitter_df['time_stamp']):
        
        # convert tweet timestamp to datetime format
        tweet_time = datetime.strptime(tweet_ts, '%Y-%m-%d %H:%M:%S')
        
        # loop through every outage in the state power df
        for j, start_ts in enumerate(state_power_df['Date Event Began']):
            
            # convert the start time to datetime format
            event_start_str = start_ts + " " + state_power_df['Time Event Began'][state_power_df['state'].index[j]]
            start_time = datetime.strptime(event_start_str, '%Y-%m-%d %H:%M:%S')

            # convert the restoration time to dattime format
            resto_str = state_power_df['Date of Restoration'][state_power_df['state'].index[j]] + " " + state_power_df['Time of Restoration'][state_power_df['state'].index[j]]

            # we need this try/except because some Dates and Times of resotration are unknowns, so we're going to 
            # set resto_time to be equal to one day after start time (may need to change this)
            try:
                resto_time = datetime.strptime(resto_str, '%m/%d/%Y %H:%M:%S')
            except:
                resto_time = start_time + timedelta(days=1)

            # check if tweet_time is in between start_time and resto_time
            if (tweet_time >= start_time) and (tweet_time <= resto_time):
                twitter_df['target'][state_twitter_df['location'].index[i]] = 1
    
    if (round((counter / size)*100) % 5 == 0) and round((counter / size)*100) > 0:
        print(f'{round((counter / size)*100)}% complete')
        print(f'{(time.time() - t0)/60} mins')
        print(f"{twitter_df['target'].sum()} total hits")
        print('---------------------')
    counter += 1
    
print('100% complete')
print(f'{(time.time() - t0)/60} mins')
print(f"{twitter_df['target'].sum()} total hits")

10% complete
0.6515756011009216 mins
0 total hits
---------------------
15% complete
0.6652002016703288 mins
0 total hits
---------------------

/Users/Creighton/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

25% complete
0.7142653505007426 mins
13 total hits
---------------------
35% complete
0.7380046168963115 mins
16 total hits
---------------------
40% complete
1.1772082686424254 mins
28 total hits
---------------------
50% complete
1.2486285010973612 mins
29 total hits
---------------------
60% complete
1.2541555047035218 mins
29 total hits
---------------------
65% complete
2.2670362830162047 mins
700 total hits
---------------------
75% complete
2.389283835887909 mins
736 total hits
---------------------
85% complete
2.5209036310513815 mins
736 total hits
---------------------
90% complete
2.9904131213823955 mins
870 total hits
---------------------
100% complete
3.0718086838722227 mins
942 total hits

In [25]:
twitter_df[twitter_df['target'] == 1]['location'].value_counts()

New York                671
Washington              134
District of Columbia     71
South Carolina           24
Georgia                  13
Massachusetts            11
Pennsylvania              8
Oregon                    3
Maine                     3
Wyoming                   1
Minnesota                 1
Maryland                  1
Oklahoma                  1
Name: location, dtype: int64

In [24]:
twitter_df.to_csv('../Data/twitter_target.csv', index=False)